### ISSUE TITLE
🐞 sitemap.xml and robots.txt not exposed + missing support for domain-driven nested routes

### ISSUE THREAD

**Issue by ghost** [Qalisa/vike-plugin-sitemap#5]
### Sitemap Routing Conflict – Reserved Keyword `page`

> However, during `preview` or `build`, I can't access:
> 
> - `mysite.com/sitemap.xml`
> - `mysite.com/robots.txt`
> 
> Even though these files are either:
> - generated in `outputDir: "dist/client" `  
> - OR manually placed, in `outputDir: "dist/cloudflare"` 
> 
> They're just not exposed in the final build, so Google can't validate them.
> 
> For context, I'm using **Vike** with the **Cloudflare** plugin.
> 
> **For now, I made this simple change as a temporary fix, :**
> `outputDir: "./public"`
> 
> 👉  However, it still doesn’t account for domain-driven nested routes like:
> `(folder)/routeFolder/+Page.jsx`
> 
> Any idea how to properly serve these static files in production?
> 
> 
> Thanks!
> @brillout @Amphaal 
> 
> Further more there is 2 logs, i don't understand why note one
> ![Image](https://github.com/user-attachments/assets/3b5ce854-fd0e-46f6-94e5-4cfc41319b7d) 

 _Originally posted by @br0wsa in [#3](https://github.com/Qalisa/vike-plugin-sitemap/issues/3#issuecomment-2777614558)_

### 📷 Example:

In a nested DDD structure (e.g., `payments`), the `page` folder is still appearing in the route path.  
However, `page` is a **reserved keyword** in Vike, and should not be part of the public URL structure.

![Image](https://github.com/user-attachments/assets/4e5643b1-a068-4075-9d56-8a9a4540d790)

🔍 View the live sitemap:  
[https://mvp.a11ystart.blue/sitemap.xml](https://mvp.a11ystart.blue/sitemap.xml)

**Comment by gg-vara** [comment]
@br0wsa,

Just clarified the usage of the plugin with the latest `1.3.0`: it will systematically produce new `robots.txt` / `sitemap.xml` files at desired and expected output bundle location, disregarding SSG / SSR specifics. `outputDir` will now specify the path, relative to the expected root of your client bundle, where the plugin will copy those files.

**Comment by gg-vara** [comment]
To clarify:

If your `vite.config.ts` looks like this:
<img width="393" alt="Image" src="https://github.com/user-attachments/assets/65762080-0eb4-4ff8-b389-f16b22aeea8a" />

... then your output folder will look like this (if you do SSR like i did for the test project)

<img width="324" alt="Image" src="https://github.com/user-attachments/assets/f4bdb2a2-5cb5-44ae-8190-83b6961316cd" />

---

On the other hand, if you specify `public`: 

<img width="411" alt="Image" src="https://github.com/user-attachments/assets/c80c710f-3310-4307-95b8-97f45ff4564f" />

... then your output folder will look like this:

<img width="278" alt="Image" src="https://github.com/user-attachments/assets/2fc4ea04-9c52-4490-8315-f400949af76e" />

Notice that the test project is not using the `public` folder for additional files, as mine only contains both generated files.

**Comment by gg-vara** [comment]
Since https://github.com/Qalisa/vike-plugin-sitemap/issues/4 is related to the other issue about domain-driven routes, I'll be closing this one and try to work on the feature later. Please feel free to propose a pull request to add it :)

**Comment by gg-vara** [comment]
<img width="451" alt="Image" src="https://github.com/user-attachments/assets/d163d884-bfb9-4fda-9967-34e7d94f5587" />

Given my latest tests, deeply nested, non dynamic SSG links are properly generated. Can you confirm this ?

**Comment by ghost** [comment]
_....almost...i just built  right now :_ 
[my_sitemap](https://mvp.a11ystart.blue/sitemap.xml)

The **📁index** and **📁pages** folders are still appearing.

@br0wsa

**Comment by gg-vara** [comment]
Can you provide a public repo with the faulty behavior ?

**Comment by ghost** [comment]
> Can you provide a public repo with the faulty behavior ?

_It appears that you have the same error in your image._  

After 'star-wars,' there are still **index** , just have a look in your own repo **;-)**
and also  **pages ** like '**index**' are treated as **folders**. 
They are folders but they appears in the routes.

Have a quick smart look 

![Image](https://github.com/user-attachments/assets/a926b7be-e9ed-4c5a-987a-cc8b0572bb88)

Info : [vike.dev/file-structure#domain-driven](https://vike.dev/file-structure#domain-driven)

**Comment by gg-vara** [comment]
gotcha ! Thanks for the hand-holding, wasn't aware or `pages` being a special keyword of Vike. Also missed the index, my bad. Update should roll in a few minutes.

**Comment by ghost** [comment]
I eagerly await your response! Wishing you an excellent weekend!

**Comment by gg-vara** [comment]
Sorry for the delay, `1.4.0` is out with both fixes ! let me know these are fixed by closing this ticket :)

**Comment by ghost** [comment]
using package.json 

    ` "@qalisa/vike-plugin-sitemap": "^1.4.0",`

and vite config 
```
 sitemap({
      baseUrl: "https://mvp.a11ystart.blue",
      filename: "sitemap.xml",
      defaultChangefreq: "weekly",
      defaultPriority: 0.5,
      robots: { userAgent: "*", disallow: { cloudflare: true } },
      outputDir: "./public",
    }),
```


- Unfortunately, the `pages` folder and the `index` folder are still appearing in the generated `sitemap.xml` 😞  
- Only folders wrapped in parentheses **e.g.** `(marketing)` are correctly excluded, as they don't appear in the final URL structure ✅  


![Image](https://github.com/user-attachments/assets/b87e0732-e850-4a8b-a8fa-799fcb932797)
![Image](https://github.com/user-attachments/assets/e5d6ca62-56fd-4673-b4fa-4aa224008c7f)

😥😥😥😥😥 nooOOOooo

you have to remove

1. **( folders wrapped in parentheses )** : it's already done
2. **pages** folder : to do
3. **index** folder : to do

### Exemple with index folder: 
 `<loc>https:/mvp.a11ystart.blue/pages/admin-panel/index</loc> `
should be 
` <loc>https:/mvp.a11ystart.blue/pages/admin-panel/</loc>`

### Exemple with pages folder : 
`<loc>https:/mvp.a11ystart.blue/pages/admin-panel/pages/analytics</loc>`
should be 
`<loc>https:/mvp.a11ystart.blue/admin-panel/analytics</loc>`

**Comment by gg-vara** [comment]
woops, it closed unexpectedly, but I hope this time these bugs are gone for good. Took the time to refactor it myself (Thanks, but no thanks Sonnet...). Let me know if it is still broken.

**Comment by ghost** [comment]
**Routes** are corrects now. **_Good news ! ;-)_**

Now it **automatically creates a public folder, right?** 

_So what is the purpose and utility of adding an outputDir parameter?_ 

Then, i have This bug, it occurs during deployment on **Cloudflare**

`Error during build:
09:07:24.097	TypeError: Cannot read properties of undefined (reading 'substring')
09:07:24.097	    at file:///opt/buildhome/repo/node_modules/.pnpm/@qalisa+vike-plugin-sitemap@1.5.2_vite@6.2.6/node_modules/@qalisa/vike-plugin-sitemap/dist/generators/sitemap.js:88:40
09:07:24.098	    at Array.map (<anonymous>)
09:07:24.098	    at getResolvedPages (file:///opt/buildhome/repo/node_modules/.pnpm/@qalisa+vike-plugin-sitemap@1.5.2_vite@6.2.6/node_modules/@qalisa/vike-plugin-sitemap/dist/generators/sitemap.js:86:38)
09:07:24.098	    at getSitemapEntries (file:///opt/buildhome/repo/node_modules/.pnpm/@qalisa+vike-plugin-sitemap@1.5.2_vite@6.2.6/node_modules/@qalisa/vike-plugin-sitemap/dist/generators/sitemap.js:164:39)
09:07:24.098	    at generateSitemapContent (file:///opt/buildhome/repo/node_modules/.pnpm/@qalisa+vike-plugin-sitemap@1.5.2_vite@6.2.6/node_modules/@qalisa/vike-plugin-sitemap/dist/generators/sitemap.js:215:21)
09:07:24.098	    at writeSitemapToDisk (file:///opt/buildhome/repo/node_modules/.pnpm/@qalisa+vike-plugin-sitemap@1.5.2_vite@6.2.6/node_modules/@qalisa/vike-plugin-sitemap/dist/generators/sitemap.js:255:28)
09:07:24.098	    at Object.closeBundle (file:///opt/buildhome/repo/node_modules/.pnpm/@qalisa+vike-plugin-sitemap@1.5.2_vite@6.2.6/node_modules/@qalisa/vike-plugin-sitemap/dist/index.js:82:13)
09:07:24.098	    at async Promise.all (index 0)
09:07:24.099	    at PluginDriver.hookParallel (file:///opt/buildhome/repo/node_modules/.pnpm/rollup@4.40.0/node_modules/rollup/dist/es/shared/node-entry.js:22090:17)
09:07:24.099	    at Object.close (file:///opt/buildhome/repo/node_modules/.pnpm/rollup@4.40.0/node_modules/rollup/dist/es/shared/node-entry.js:23101:13) {
09:07:24.099	  code: 'PLUGIN_ERROR',
09:07:24.099	  plugin: '@qalisa/vike-plugin-sitemap',
09:07:24.099	  hook: 'closeBundle'
09:07:24.099	}
09:07:24.154	Failed: Error while executing user command. Exited with error code: 1
09:07:24.164	Failed: build command exited with code: 1
09:07:25.699	Failed: error occurred while running build command`


![Image](https://github.com/user-attachments/assets/6daf8d69-e506-41fb-b02d-3843bd0d80d6)

**Comment by gg-vara** [comment]
> **Routes** are corrects now. **_Good news ! ;-)_**
> 
> Now it **automatically creates a public folder, right?**
> 
> _So what is the purpose and utility of adding an outputDir parameter?_
> 
> Then, i have This bug, it occurs during deployment on **Cloudflare**
> 
> `Error during build: 09:07:24.097 TypeError: Cannot read properties of undefined (reading 'substring') 09:07:24.097 at file:///opt/buildhome/repo/node_modules/.pnpm/@qalisa+vike-plugin-sitemap@1.5.2_vite@6.2.6/node_modules/@qalisa/vike-plugin-sitemap/dist/generators/sitemap.js:88:40 09:07:24.098 at Array.map (<anonymous>) 09:07:24.098 at getResolvedPages (file:///opt/buildhome/repo/node_modules/.pnpm/@qalisa+vike-plugin-sitemap@1.5.2_vite@6.2.6/node_modules/@qalisa/vike-plugin-sitemap/dist/generators/sitemap.js:86:38) 09:07:24.098 at getSitemapEntries (file:///opt/buildhome/repo/node_modules/.pnpm/@qalisa+vike-plugin-sitemap@1.5.2_vite@6.2.6/node_modules/@qalisa/vike-plugin-sitemap/dist/generators/sitemap.js:164:39) 09:07:24.098 at generateSitemapContent (file:///opt/buildhome/repo/node_modules/.pnpm/@qalisa+vike-plugin-sitemap@1.5.2_vite@6.2.6/node_modules/@qalisa/vike-plugin-sitemap/dist/generators/sitemap.js:215:21) 09:07:24.098 at writeSitemapToDisk (file:///opt/buildhome/repo/node_modules/.pnpm/@qalisa+vike-plugin-sitemap@1.5.2_vite@6.2.6/node_modules/@qalisa/vike-plugin-sitemap/dist/generators/sitemap.js:255:28) 09:07:24.098 at Object.closeBundle (file:///opt/buildhome/repo/node_modules/.pnpm/@qalisa+vike-plugin-sitemap@1.5.2_vite@6.2.6/node_modules/@qalisa/vike-plugin-sitemap/dist/index.js:82:13) 09:07:24.098 at async Promise.all (index 0) 09:07:24.099 at PluginDriver.hookParallel (file:///opt/buildhome/repo/node_modules/.pnpm/rollup@4.40.0/node_modules/rollup/dist/es/shared/node-entry.js:22090:17) 09:07:24.099 at Object.close (file:///opt/buildhome/repo/node_modules/.pnpm/rollup@4.40.0/node_modules/rollup/dist/es/shared/node-entry.js:23101:13) { 09:07:24.099 code: 'PLUGIN_ERROR', 09:07:24.099 plugin: '@qalisa/vike-plugin-sitemap', 09:07:24.099 hook: 'closeBundle' 09:07:24.099 } 09:07:24.154 Failed: Error while executing user command. Exited with error code: 1 09:07:24.164 Failed: build command exited with code: 1 09:07:25.699 Failed: error occurred while running build command`
> 
> ![Image](https://github.com/user-attachments/assets/6daf8d69-e506-41fb-b02d-3843bd0d80d6)

The plugin should now normally put the sitemap.xml + robots.txt in the correct location inside your bundle, should not need to set `outDir` anymore. We'll track the Cloudflare issue in the other ticket then, I'll close this one 👍

**Comment by ghost** [comment]
**_OK nice... smooth like a 🍦._**
But there's another issue.

Before, I was able to access the generated `/sitemap.xml ` at ` www.url/sitemap.xml`.

**Now, the file is missing.**

That’s why I previously had the `outputDir set to public` — _so the sitemap would be publicly accessible._
Currently, the file is only available in the **dist or client folder** after the build, but it’s not served publicly, so Google can’t access it.

I'm using Vite (via Bati), deployed on Cloudflare, with React.

![Image](https://github.com/user-attachments/assets/ac357b91-98c6-457c-9837-5c8d7cb64865)
![Image](https://github.com/user-attachments/assets/b98c5b4a-e223-4c23-880d-43bcade6f6f2)
![Image](https://github.com/user-attachments/assets/a7cd94f8-b35a-4ed7-ae06-04a422f8e6fe)
![Image](https://github.com/user-attachments/assets/fd76c7c7-a6a7-47e8-a972-38cd2d424ef0)
